repository: ethereum/go-ethereum

theme: minima

keep_files:
  - static

favicon: /static/images/favicon.png

defaults:
  - scope:
      path: ""
    values:
      layout: sidebar
  - scope:
      path: "*"
    values:
      root: "."
  - scope:
      path: "*/*"
    values:
      root: ".."

default_root: ".."

collections_dir: docs
collections:
  install-and-build:
    output: true
    caption: Install and build
    sidebar_index: 1
  how-to:
    output: true
    caption: How to use
    sidebar_index: 2
  interface:
    output: true
    caption: Interface documentation
    sidebar_index: 3
  support:
    output: true
    caption: Issues and support
    sidebar_index: 4
  developers:
    output: true
    caption: Developers
    sidebar_index: 5
  clef:
    output: true
    caption: Clef
    sidebar_index: 6
  doc:
    output: true
    caption: Other
    sidebar_index: 7

